// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/gutrse3321/aki/pkg/app"
	"github.com/gutrse3321/aki/pkg/config"
	"github.com/gutrse3321/aki/pkg/log"
	"github.com/gutrse3321/aki/pkg/transports/http"
	"github.com/gutrse3321/web-marisa/src"
	"github.com/gutrse3321/web-marisa/src/controller"
)

// Injectors from wire.go:

func CreateApp(configPath string) (*app.Application, error) {
	viper, err := config.New(configPath)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.New(options)
	if err != nil {
		return nil, err
	}
	appOptions, err := src.NewOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	httpOptions, err := http.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	indexController := controller.NewIndexController()
	initControllers := controller.CreateInitControllersFn(indexController)
	engine := http.NewRouter(httpOptions, logger, initControllers)
	server, err := http.New(httpOptions, logger, engine)
	if err != nil {
		return nil, err
	}
	application, err := src.NewApp(appOptions, logger, server)
	if err != nil {
		return nil, err
	}
	return application, nil
}

// wire.go:

/**
 * @Author: Tomonori
 * @Date: 2021/8/12
 * @Title:
 * --- --- ---
 * @Desc:
 */
var wireSet = wire.NewSet(log.WireSet, config.WireSet, http.WireSet, src.ProviderSet, controller.ProviderSet)
